[package]
name = "rush"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
paste = "1.0.15"
rust_decimal = { version = "1.37", features = ["macros", "maths"] }
rush_macro = { path = "rush_macro" }