on: [ push, pull_request ]

jobs:
  check:
    name: Test-Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test